import DS from 'ember-data';

var Product = DS.Model.extend({
	name: DS.attr('string'),
	title: DS.attr('string'),
	logo: DS.attr('string'),
	pic: DS.attr('string'),
	icon1: DS.attr('string'),
	icon1_desc: DS.attr('string'),
	icon2: DS.attr('string'),
	icon2_desc: DS.attr('string'),
	icon3: DS.attr('string'),
	icon3_desc: DS.attr('string'),
	icon4: DS.attr('string'),
	icon4_desc: DS.attr('string'),
	icon5: DS.attr('string'),
	icon5_desc: DS.attr('string')
});

Product.reopenClass({
	FIXTURES: [{
		id: 1,
		name: "飞鱼配送",
		title: "快递员专属",
		logo: "images/products/logo/feiyu_active.png",
		pic: "images/products/logo/feiyu_active.png",
		icon1: "images/products/feiyu_safe.png",
		icon1_desc: "查单打电话自动屏蔽手机号，自动删除通话记录，保障客户信息安全。",
		icon2: "images/products/feiyu_bianjie.png",
		icon2_desc: "摇一摇送货，随时查单打电话；签收信息拍照上传；微信和支付宝快捷支付、多单提交。",
		icon3: "images/products/feiyu_touming.png",
		icon3_desc: "app数据与PC端数据实时同步，配送员实时了解自身任务和提成。",
		icon4: "",
		icon4_desc: "",
		icon5: "",
		icon5_desc: ""
	},{
		id: 2,
		name: "风云系统",
		title: "配送SaaS平台",
		logo: "images/products/logo/fengyun_active.png",
		pic: "images/products/logo/fengyun_active.png",
		icon1: "images/products/feiyu_safe.png",
		icon1_desc: "https、md5、3DES加密、第四代防火墙、ISO9001、ISO27001体系认证、特殊客户电话拨号加密等，让您的信息\"滴水不露\"。",
		icon2: "images/products/shishi.png",
		icon2_desc: "订单来源分析、订单去向分析；商家单量分析、历史订单分析；总成本监控、各部门成本监控、商家收入分析、利润分析；分拣效率监控、运输效率监控、站点效率监控。",
		icon3: "images/products/shezhi.png",
		icon3_desc: "支持200万单/天，系统可靠性99.99%，三个机房300台服务器，支持各业务高并发量，多个完整的配套系统，完整的服务体系，为您提供强大的业务保障。",
		icon4: "images/products/duopingtai.png",
		icon4_desc: "电商派件、上门换货、快递等多种特色业务，系统支持供应链、O2O等多种业务模式。",
		icon5: "images/products/gongyinglian.png",
		icon5_desc: "上游对接近300家知名商家，与主流电商及平台基本实现无缝对接，并对接多家电视购物平台；下游对接超过50家配送商。"
	},{
		id: 3,
		name: "嘟嘟好运",
		title: "让物流更顺畅",
		logo: "images/products/logo/dudu_active.png",
		pic: "images/products/logo/dudu_active.png",
		icon1: "images/products/feiyu_safe.png",
		icon1_desc: "AAAAA级物流公司--天地华宇集团进行严格的司机及车辆审核认证，提供整车货物保险、正规发票，全程在线货物跟踪服务，为您的货物保价护航。",
		icon2: "images/products/feiyu_bianjie.png",
		icon2_desc: "在线询价，流程简单方便，提供手机APP、官方网站、微信、400电话多种方式发货，无需等待快速处理精准安排，各款车型车源充足，覆盖全国。",
		icon3: "images/products/dodo_shihui.png",
		icon3_desc: "平台依托于天地华宇集团运力资源，拥有大量回程车源，运费低于市场平均整车价格。",
		icon4: "",
		icon4_desc: "",
		icon5: "",
		icon5_desc: ""
	},{
		id: 4,
		name: "华师傅",
		title: "移动运营管理工具",
		logo: "images/products/logo/huashifu_active.png",
		pic: "images/products/huashifu_show.png",
		icon1: "images/products/shixiao.png",
		icon1_desc: "从受理、揽收，到开单、提货、送货，再到签收，每一步都由系统智能监控，货运的每一步，都在您的掌控之中，用得放心。",
		icon2: "images/products/fuzhu.png",
		icon2_desc: "扫一扫、打印、货物跟踪查询、常用目的地等使用功能帮助司机师傅提升服务质量，更贴心舒适的服务体验。",
		icon3: "",
		icon3_desc: "",
		icon4: "",
		icon4_desc: "",
		icon5: "",
		icon5_desc: ""
	},{
		id: 5,
		name: "WMS",
		title: "",
		logo: "images/products/logo/wms_active.png",
		pic: "",
		icon1: "",
		icon1_desc: "",
		icon2: "",
		icon2_desc: "",
		icon3: "",
		icon3_desc: "",
		icon4: "",
		icon4_desc: "",
		icon5: "",
		icon5_desc: ""
	},{
		id: 6,
		name: "行销",
		title: "移动CRM",
		logo: "images/products/logo/xingxiao_active.png",
		pic: "images/products/xingxiao_show.png",
		icon1: "images/products/kehuguanli.png",
		icon1_desc: "为销售人员日常工作提供便捷，维护客户信息、维系客户、以及销售人员间的沟通，提供更高效的解决方案，提高其营销效率。",
		icon2: "images/products/xitongguanli.png",
		icon2_desc: "系统会记录销售人员的销售行为和销售过程，为销售管理人员管控销售过程和销售结果提供全方位的支持，同时辅助高层领导作出关键性的营销决策。",
		icon3: "images/products/danganguanli.png",
		icon3_desc: "消息管理、订单管理、报表管理和上下级互访，并以辅助功能模块包括公司网点查询、价格时效查询、历史查询等功能，为销售人员的销售过程提供支持。",
		icon4: "",
		icon4_desc: "",
		icon5: "",
		icon5_desc: ""
	},{
		id: 7,
		name: "极送",
		title: "每人都是快递员",
		logo: "images/products/logo/jisong_active.png",
		pic: "images/products/jisong_show.png",
		icon1: "images/products/safe.png",
		icon1_desc: "众包人员抢单后系统自动冻结等值货款，实现货物零风险；配送员、商家充值、实时计算配送、T+1天提现。系统实现自动化。",
		icon2: "images/products/duopingtai.png",
		icon2_desc: "支持普通用户、小商家平台发布配送需求；支持大商家、平台订单对接；支持站点提前布库存。满足不同用户的不同需求，实现业务定制化。",
		icon3: "images/products/shenhe.png",
		icon3_desc: "支持众包，人员进入、审核、认证、培训、考核机制完善，通过配送人员的配送数据，以及客户的评价信息，对众包人员进行综合评级。",
		icon4: "images/products/fenpei.png",
		icon4_desc: "系统根据配送距离、配送员任务、配送员等级、配送时效、订单要求等各种维度，进行科学、合理的订单匹配，人员调度，实现O2O配送对时效的特殊要求。",
		icon5: "",
		icon5_desc: ""
	}]
});

export default Product;